classdef TestFieldNames < matlab.unittest.TestCase

  methods (Test)

    function testValidation(testCase)
      invalid_inputs = { ...
          {'a', 'b', 'c'} ...
        , [1, 2, 3, 4] ...
        , 'string' ...
                       };

      for indx = 1:numel(invalid_inputs)
        testCase.verifyError( ...
            @() s_utils.field_names(invalid_inputs{indx}), ...
            'MATLAB:InputParser:ArgumentFailedValidation', ...
            'Did not reject invalid input.' ...
            )
      end
    end

    function testNonRecursive(testCase)
      data = struct( ...
          'a', [] ...
        , 'b', struct( ...
            'c', [] ...
          , 'd', struct( ...
              'e', [] ...
              ) ...
            ) ...
          );

      result = {'a'; 'b'};

      testCase.verifyEqual( ...
          s_utils.field_names(data), ...
          result, ...
          'Did not get top-level field names correctly.')
    end

    function testRecursive(testCase)
      data = struct( ...
          'a', [] ...
        , 'b', struct( ...
            'c', [] ...
          , 'd', struct( ...
              'e', [] ...
              ) ...
            ) ...
          );

      result = {{'a'}; {'b', 'c'}; {'b', 'd', 'e'}};

      testCase.verifyEqual( ...
          s_utils.field_names(data, 'recursive', true), ...
          result, ...
          'Did not get recursive field names correctly.')
    end

  end

end